name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Permisos requeridos para desplegar oficialmente en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue concurrente a la vez
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 3. Install dependencies
        run: flutter pub get

      - name: 4. Build Flutter web
        run: flutter build web --release --base-href /mi_portafolio_web/

      - name: 5. Setup Pages
        uses: actions/configure-pages@v5

      - name: 6. Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/web'

      - name: 7. Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4